package ro.iteahome.nhs.backend.model.nhs.reference;

public enum NurseSpecialty { // TODO: Show these in a web page dropdown and concatenate multiple choices into a single string.

    REGISTERED_NURSE,
    CARDIAC_NURSE,
    CERTIFIED_REGISTERED_NURSE_ANESTHETIST,
    CLINICAL_NURSE_SPECIALIST,
    CRITICAL_CARE_NURSE,
    ER_NURSE,
    FAMILY_NURSE_PRACTITIONER,
    GERIATRIC_NURSING,
    PERIOPERATIVE_NURSE,
    MENTAL_HEALTH_NURSE,
    NURSE_EDUCATOR,
    NURSE_MANAGER,
    NURSE_MIDWIFE,
    NURSE_PRACTITIONER,
    NURSING_ADMINISTRATOR,
    ONCOLOGY_NURSE,
    ORTHOPEDIC_NURSE,
    PEDIATRIC_NURSE,
    PUBLIC_HEALTH_NURSE,
    TRAVEL_NURSE

}
